# Generated by Django 5.0.6 on 2025-08-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gown',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
