# Generated by Django 5.0.6 on 2025-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection1', '0002_gown_description_gown_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidsDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='maids_dresses/')),
            ],
        ),
    ]
